### ISSUE TITLE
INVALID_TYPE_ON_FIELD_IN_RECORD  error for numeric values

### ISSUE THREAD

**Issue by jira** [p5-salesforce/WWW-Salesforce#18]
Hi,

upsert/create/insert not working for me. I always get an INVALID_TYPE_ON_FIELD_IN_RECORD error for any numeric value. I tried to specify numbers in every possible format I can phantom, but to no avail.

An ideas

**Comment by genio** [comment]
We will be happy to re-open this if you have more information.  Just let us know.
