### ISSUE TITLE
TLS 1.1 not used. TLS 1.0 No longer supported

### ISSUE THREAD

**Issue by eamon-r** [p5-salesforce/WWW-Salesforce#23]

**Comment by genio** [comment]
@eamon-r What OS and what version of OpenSSL are you on?  WWW::Salesforce makes use of SOAP::Lite.  SOAP::Lite uses LWP::UserAgent for transport.

LWP::UserAgent ends up using IO::Socket::SSL in the end.  IO::Socket::SSL makes use of your version of OpenSSL.  If you can narrow down your OS, Perl version, and OpenSSL version for us, it might help us find the solution.

**Comment by eamon-r** [comment]
My apologies for the incomplete info earlier. 

Sadly this integration runs in Windows server currently. 

Summary of my perl5 (revision 5 version 14 subversion 2) configuration:

  Platform:
    osname=MSWin32, osvers=5.2, archname=MSWin32-x86-multi-thread
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cl', ccflags ='-nologo -GF -W3 -MD -Zi -DNDEBUG -O1 -DWIN32 -D_CONSOLE -DNO_STRICT -DPERL_TEXTMODE_SCRIPTS -DUSE
_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D_USE_32BIT_TIME_T',
    optimize='-MD -Zi -DNDEBUG -O1',
    cppflags='-DWIN32'
    ccversion='12.00.8168', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='__int64', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='link', ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf  -libpath:"C:\Perl\lib\CORE"  -machine:x86'
    libpth=\lib
    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib ol
eaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.
lib
    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.li
b oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msv
crt.lib
    libc=msvcrt.lib, so=dll, useshrplib=true, libperl=perl514.lib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -debug -opt:ref,icf  -libpath:"C:\Perl\lib\CORE"  -machine:x86
'


Characteristics of this binary (from libperl):
  Compile-time options: MULTIPLICITY PERL_DONT_CREATE_GVSV
                        PERL_IMPLICIT_CONTEXT PERL_IMPLICIT_SYS
                        PERL_MALLOC_WRAP PERL_PRESERVE_IVUV PL_OP_SLAB_ALLOC
                        USE_ITHREADS USE_LARGE_FILES USE_PERLIO USE_PERL_ATOF
                        USE_SITECUSTOMIZE
  Locally applied patches:
        ActivePerl Build 1402 [295342]
  Built under MSWin32
  Compiled at Oct  7 2011 15:49:44
  @INC:
    C:/Perl/site/lib
    C:/Perl/lib
   
Updated www::salesforce to 0.25

SOAP-Lite  Perl's Web Services Toolkit
	Version:	1.19
	Released:	2015-08-26

IO-Socket-SSL
Nearly transparent SSL encapsulation for IO::Socket::INET.
	Version:	1.44
	Released:	2011-05-27

**Comment by genio** [comment]
@eamon-r At a first glance, the version of IO::Socket::SSL you're using is pretty old.  Can you update that as a first step, please?

**Comment by eamon-r** [comment]
My sincere apologies on this one. I had used PPM and it said I had the latest avail. Used cpan and am up to 2.024 now on IO::Socket::SSL and I also pulled Net::SSLeay up to 1.72 to get rid of the random number gen bug. Hope this helps someone else. 

genio, much thanks for your assist. I should have ran these down myself, but thought I was up to date. I'll double check in the future.

**Comment by genio** [comment]
No problem at all.  I'm glad it was an easy fix!  Don't hesitate to bring up issues if you have them in the future.
