### ISSUE TITLE
UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https. at /home/site_per/salesforce.pm line 506

### ISSUE THREAD

**Issue by chaudharynitin** [p5-salesforce/WWW-Salesforce#24]
CentOS release 6.5 (Final)

perl 5, version 12, subversion 2 (v5.12.2) built for x86_64-linux-thread-multi

use WWW::Salesforce::Simple;
my $sforce = WWW::Salesforce::Simple->new(
		'username' => 'username',
                'password' => 'password',
                'serverurl' => ''
                );

**Comment by genio** [comment]
@chaudharynitin WWW::Salesforce uses SOAP::Lite and thus, LWP::UserAgent. LWP::UserAgent uses LWP::Protocol::https which uses IO::Socket::SSL for sending requests over HTTPS.  IO::Socket::SSL makes use of the OpenSSL installed on your system.

I have a few questions about your setup that may help us figure out what's going on:

1. Since 5.12 doesn't ship on CentOS 6 by default, how did you install this version? (using another repo set? Using PerlBrew/PLenv/Perl::Build?
1. What version of OpenSSL is installed? (```yum info openssl```)
1. What version of each of the Perl modules listed above do you have?
  * ```perl -MIO::Socket::SSL\ 99999 -E 0```
  * ```perl -MLWP::Protocol::https\ 99999 -E 0```
  * ```perl -MLWP::UserAgent\ 99999 -E 0```
  * ```perl -MSOAP::Lite\ 99999 -E 0```
  * ```perl -MWWW::Salesforce\ 99999 -E 0```

**Comment by genio** [comment]
Sorry about that. I didn't mean to click the close button.

**Comment by chaudharynitin** [comment]
Please accept my sincere apologies, i provide wrong OS detail in last thread.

OS : Red Hat Enterprise Linux Client release 5.5 (Tikanga) 

perl :  5, version 12, subversion 2 (v5.12.2) built for x86_64-linux-thread-multi

openssl version:  OpenSSL 1.0.1e 11 Feb 2013

/grid/test/bin/perl -MWWW::Salesforce\ 99999
WWW::Salesforce version 99999 required--this is only version 0.22.
BEGIN failed--compilation aborted.


/grid/test/bin/perl -MSOAP::Lite\ 99999
SOAP::Lite version 99999 required--this is only version 1.13.
BEGIN failed--compilation aborted.

/grid/test/bin/perl -MLWP::UserAgent\ 99999
LWP::UserAgent version 99999 required--this is only version 6.06.
BEGIN failed--compilation aborted.

/grid/test/bin/perl -MLWP::Protocol::https\ 99999
LWP::Protocol::https version 99999 required--this is only version 6.06.
BEGIN failed--compilation aborted.

/grid/test/bin/perl -MIO::Socket::SSL\ 99999
IO::Socket::SSL version 99999 required--this is only version 2.007.
BEGIN failed--compilation aborted.

Please Help .

**Comment by genio** [comment]
@chaudharynitin At a glance, your versions of everything look to be good enough for ```TLSv1.1``` and ```TLSv1.2```.

Out of curiosity, how are you installing Perl modules? The Perl you have you seem to have installed yourself, so I don't think you're using system Perl.  There are newer versions of IO::Socket::SSL out there, but yours _appears_ to be new enough to support TLSv1.1 and 1.2.  A simple test to see if IO::Socket::SSL is capable of communicating would be:

```bash
perl -MIO::Socket::SSL -E 'my $c=IO::Socket::SSL->new(PeerHost=>q(login.salesforce.com),PeerPort=>q(https)) or die "Failed: $!, $SSL_ERROR"; print $c "GET /services/Soap/u/37/ HTTP/1.0\r\n\r\n"; say <$c>'
```

That _should_ give you something like:

```
HTTP/1.1 500 Server Error
Date: Tue, 09 May 2017 13:49:08 GMT
Set-Cookie: BrowserId=lucj0aAwRtyQVeAwWyugXw;Path=/;Domain=.salesforce.com;Expires=Sat, 08-Jul-2017 13:49:08 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/xml; charset=UTF-8
Connection: close

<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sf="urn:fault.partner.soap.sforce.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>UNKNOWN_EXCEPTION</faultcode><faultstring>UNKNOWN_EXCEPTION: Failed to read POST: POST requires content-length</faultstring><detail><sf:UnexpectedErrorFault xsi:type="sf:UnexpectedErrorFault"><sf:exceptionCode>UNKNOWN_EXCEPTION</sf:exceptionCode><sf:exceptionMessage>Failed to read POST: POST requires content-length</sf:exceptionMessage></sf:UnexpectedErrorFault></detail></soapenv:Fault></soapenv:Body></soapenv:Envelope>
```

However, if that fails, the next step would be to update your version of IO::Socket::SSL.

Thanks,
Chase

**Comment by genio** [comment]
With the release of version 0.301 now out there: https://metacpan.org/release/CAPOEIRAB/WWW-Salesforce-0.301 we have a clear prerequisite listed for ```IO::Socket::SSL``` now. We shouldn't have these issues anymore.
