### ISSUE TITLE
Version 8 of the Salesforce SOAP API has been deprecated and will be dropped.

### ISSUE THREAD

**Issue by vickersa1** [p5-salesforce/WWW-Salesforce#28]
Salesforce recently announced that versions 22.0 and lower of the SOAP API has been deprecated and is no longer supported. Requests to this version will be rejected after the Summer 2022 release. In addition, the Summer 2022 release will deprecate versions 21 through 30.

WWW::Salesforce appears to be using Version 8.0 and will cease to function around June/July 2022.

As of the time of writing, the most recent SOAP API version is 52.0.

**Comment by genio** [comment]
Thanks. We'll update and cut a release soon.
